ignore:
  - node_modules/

eslint:
  enabled: true
  config_file: .eslintrc.json
  extensions:
    - .js
    - .ts
    - .tsx
  exclude_files:
    - test/**
    - spec/**

javascript:
  enabled: false
