ignore:
  - node_modules/

eslint:
  enabled: true
  config_file: .eslintrc.config.mjs
  extensions:
    - .js
    - .mjs
    - .cjs
    - .jsx
  exclude_files:
    - test/**
    - spec/**

javascript:
  enabled: false
